import { Inter, Raleway, Poppins } from 'next/font/google'
import './styles/globals.css'
import Header  from './components/header'

const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })
const poppins = Poppins({ subsets: ['latin'], weight: ['200', '300', '400', '500'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Header></Header>
        {children}
      </body>
    </html>
  )
}
